### ISSUE TITLE
The image brightness is saturated after doing deconvolution

### ISSUE THREAD

**Issue by poisonivyy96** [DanuserLab/u-surface3D#7]
I want to use data that I have acquired using SPIM. But when I choose deconvolution and mesh, after deconvolution I get that image brightness is saturated and then in the next step (mesh) software freezes. I don´t know what could be the problem. Is there maybe a way to adjust psf file to fit to our set-up? Or is there some other way to deal with this problem? Thank you in advance

![Screenshot_20230713_110726](https://github.com/DanuserLab/u-shape3D/assets/113446663/daf40459-4b9b-42eb-9a7e-c8568ce4a140)

**Comment by DanuserLab** [comment]
Thank you for reaching out. Sorry for the delayed response. For assistance with this, it might be helpful to contact the authors directly via email. Introducing yourself, explaining your project, and describing the issue you're encountering, along with your dataset if appropriate, could provide valuable context for them to offer tailored support. We’ll close this issue for now, but don’t hesitate to reach out if further support is needed.

**Comment by DanuserLab** [comment]
If you’re still interested in a solution, here’s a suggestion: There's a particular line of code that multiples the deconvolved image by a number to increase the dynamic range of the image. That number may have to be reduced for some images. We hope this is helpful!
