### ISSUE TITLE
Related to closed issue/8

### ISSUE THREAD

**Issue by aarpon** [DanuserLab/u-surface3D#9]
Hi,

I hoped that by replying to a closed issue it would be reopened. No luck.

I had a very quick look into [issue 8](https://github.com/DanuserLab/u-shape3D/issues/8) reported by @GermanCamargoOrtega when running Example 1 from Morphology3DPackage.pdf.

As far as I can see, **Step 3: Mesh** will only work **on Windows** if one replaces the `parfor` in `meshMovieMD.m` line 210 with a normal `for` and **steps through the code in debug mode**. If the function runs of its own accord it will fail with the `array exceeds maximum array size preference` error; I couldn't figure out where exactly it fails. I tried with both MATLAB R2021b and R2024b.

I didn't face any issues in Linux (Ubuntu 24.04.1 LTS) using MATLAB R2023a.

**Comment by DanuserLab** [comment]
Thank you very much for you feedback!

We re-opened [issue 8](https://github.com/DanuserLab/u-shape3D/issues/8). Please check there for the latest solution.
